export const AVAILABLE_BANKS = [
  {
    id: 'hdfc',
    name: 'HDFC Bank',
    shortName: 'HDFC',
    tagline: 'Leading Private Sector Bank',
    tag: 'Fast Track AI Processing',
    minRate: '8.50%',
    color: 'from-blue-600 to-indigo-700',
    accentColor: 'border-blue-500/40 bg-blue-500/10 text-blue-400',
    bgBadge: 'bg-blue-600',
    initials: 'HDFC',
    description: 'Instant paperless verification, high loan amounts, and flexible repayment terms.',
  },
  {
    id: 'sbi',
    name: 'State Bank of India',
    shortName: 'SBI',
    tagline: 'Largest Public Sector Bank',
    tag: 'Lowest Interest Rates',
    minRate: '8.40%',
    color: 'from-sky-600 to-cyan-700',
    accentColor: 'border-sky-500/40 bg-sky-500/10 text-sky-400',
    bgBadge: 'bg-sky-600',
    initials: 'SBI',
    description: 'Trusted sovereign reliability, transparent fees, and widespread accessibility.',
  },
  {
    id: 'icici',
    name: 'ICICI Bank',
    shortName: 'ICICI',
    tagline: 'Instant Digital Sanction',
    tag: 'Pre-Approved Offers',
    minRate: '8.75%',
    color: 'from-amber-600 to-orange-700',
    accentColor: 'border-amber-500/40 bg-amber-500/10 text-amber-400',
    bgBadge: 'bg-amber-600',
    initials: 'ICICI',
    description: 'Express loan sanction within hours, 100% digital onboarding, and zero prepay penalties.',
  },
  {
    id: 'axis',
    name: 'Axis Bank',
    shortName: 'AXIS',
    tagline: 'Flexible Tenures & Value',
    tag: 'High LTV Ratio',
    minRate: '8.90%',
    color: 'from-rose-600 to-pink-700',
    accentColor: 'border-rose-500/40 bg-rose-500/10 text-rose-400',
    bgBadge: 'bg-rose-600',
    initials: 'AXIS',
    description: 'Custom EMI structures, high eligibility multiplier, and special corporate perks.',
  },
  {
    id: 'kotak',
    name: 'Kotak Mahindra Bank',
    shortName: 'KOTAK',
    tagline: 'Minimal Documentation',
    tag: 'Quick Disbursal',
    minRate: '8.80%',
    color: 'from-red-600 to-red-800',
    accentColor: 'border-red-500/40 bg-red-500/10 text-red-400',
    bgBadge: 'bg-red-600',
    initials: 'KOTAK',
    description: 'Swift approval for salaried professionals with seamless doorstep or digital KYC.',
  },
  {
    id: 'bob',
    name: 'Bank of Baroda',
    shortName: 'BOB',
    tagline: 'Zero Hidden Charges',
    tag: 'Low Processing Fees',
    minRate: '8.60%',
    color: 'from-orange-600 to-amber-800',
    accentColor: 'border-orange-500/40 bg-orange-500/10 text-orange-400',
    bgBadge: 'bg-orange-600',
    initials: 'BOB',
    description: 'Attractive rate linked to repo rate with full transparency on fee components.',
  },
];

export const LOAN_TYPE_DETAILS = [
  {
    value: 'personal',
    label: 'Personal Loan',
    subtitle: 'Unsecured financing for personal goals, travel, or medical needs',
    rateRange: '10.50% - 14.50%',
    tenure: 'Up to 5 Years',
    iconName: 'User',
  },
  {
    value: 'home',
    label: 'Home Loan',
    subtitle: 'Purchase, construct, or renovate residential real estate',
    rateRange: '8.40% - 9.50%',
    tenure: 'Up to 30 Years',
    iconName: 'Home',
  },
  {
    value: 'business',
    label: 'Business Loan',
    subtitle: 'Working capital, machinery, and growth capital for enterprises',
    rateRange: '12.50% - 16.00%',
    tenure: 'Up to 4 Years',
    iconName: 'Briefcase',
  },
  {
    value: 'lap',
    label: 'Loan Against Property (LAP)',
    subtitle: 'Unlock maximum liquidity by mortgaging commercial or residential property',
    rateRange: '9.00% - 11.50%',
    tenure: 'Up to 15 Years',
    iconName: 'Building',
  },
  {
    value: 'education',
    label: 'Education Loan',
    subtitle: 'Undergraduate and postgraduate studies in India and overseas',
    rateRange: '9.25% - 11.75%',
    tenure: 'Up to 15 Years',
    iconName: 'GraduationCap',
  },
  {
    value: 'vehicle',
    label: 'Vehicle / Auto Loan',
    subtitle: 'Drive your new car or commercial vehicle with instant approval',
    rateRange: '8.75% - 10.50%',
    tenure: 'Up to 7 Years',
    iconName: 'Car',
  },
];
